# from dotenv import load_dotenv

# load_dotenv()

# import asyncio

# from fastapi import FastAPI, HTTPException
# from fastapi.middleware.cors import CORSMiddleware
# from fastapi.responses import FileResponse

# from api.payment_routes import router as payment_router
# from api.routes import router
# from services.pdf_builder import ensure_output_dir, get_pdf_path

# from fastapi import WebSocket, WebSocketDisconnect

# from api.websocket_manager import manager
# from api.chat_routes import router as chat_router
# from api.voice_routes import router as voice_router

# from api.contact_routes import router as contact_router
# from api.admin_routes import router as admin_router
from dotenv import load_dotenv
print("1: dotenv")

load_dotenv()

import asyncio
print("2: asyncio")

from fastapi import FastAPI, HTTPException
print("3: fastapi")

from fastapi.middleware.cors import CORSMiddleware
print("4: cors")

from fastapi.responses import FileResponse
print("5: responses")

from api.payment_routes import router as payment_router
print("6: payment")



print("7: before routes")
from api.routes import router
print("7: after routes")

from services.pdf_builder import ensure_output_dir, get_pdf_path
print("8: pdf")

from fastapi import WebSocket, WebSocketDisconnect
print("9: websocket")

from api.websocket_manager import manager
print("10: ws manager")

from api.chat_routes import router as chat_router
print("11: chat")

from api.voice_routes import router as voice_router
print("12: voice")

from api.contact_routes import router as contact_router
print("13: contact")

from api.admin_routes import router as admin_router
print("14: admin")

app = FastAPI(title="TravelMaster API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)
app.include_router(payment_router)
app.include_router(chat_router)
app.include_router(voice_router)
app.include_router(contact_router)
app.include_router(admin_router)

@app.on_event("startup")
async def on_startup() -> None:
    # Phase 5 fix: capture the running event loop so the sync
    # /plan-trip endpoint (running in a threadpool) can schedule
    # websocket sends onto it via run_coroutine_threadsafe instead
    # of creating/destroying a new loop per event with asyncio.run().
    manager.set_loop(asyncio.get_running_loop())

    # Objective 5.4: make sure the local-disk PDF output folder
    # exists before any /generate-pdf request comes in.
    ensure_output_dir()


@app.websocket("/ws/progress/{client_id}")
async def websocket_progress(
    websocket: WebSocket,
    client_id: str,
):
    await manager.connect(client_id, websocket)

    try:
        while True:
            await websocket.receive_text()

    except WebSocketDisconnect:
        manager.disconnect(client_id, websocket)


@app.get("/download-pdf/{session_id}")
def download_pdf(session_id: str):
    """
    Objective 5.4 — serves the PDF generated by the /generate-pdf
    background task. 404s if the PDF isn't ready yet (or generation
    failed) rather than blocking/waiting on it.
    """
    path = get_pdf_path(session_id)

    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail="PDF not found. It may still be generating or generation failed.",
        )

    return FileResponse(
        path=str(path),
        media_type="application/pdf",
        filename=f"trip-{session_id}.pdf",
    )


@app.get("/")
def root():
    return {"status": "ok"}