from dotenv import load_dotenv

load_dotenv()

import asyncio

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

from api.payment_routes import router as payment_router
from api.routes import router
from services.pdf_builder import ensure_output_dir, get_pdf_path

from fastapi import WebSocket, WebSocketDisconnect

from api.websocket_manager import manager
app = FastAPI(title="TravelMaster API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)
app.include_router(payment_router)


@app.on_event("startup")
async def on_startup() -> None:
    # Phase 5 fix: capture the running event loop so the sync
    # /plan-trip endpoint (running in a threadpool) can schedule
    # websocket sends onto it via run_coroutine_threadsafe instead
    # of creating/destroying a new loop per event with asyncio.run().
    manager.set_loop(asyncio.get_running_loop())

    # Objective 5.4: make sure the local-disk PDF output folder
    # exists before any /generate-pdf request comes in.
    ensure_output_dir()


@app.websocket("/ws/progress/{client_id}")
async def websocket_progress(
    websocket: WebSocket,
    client_id: str,
):
    await manager.connect(client_id, websocket)

    try:
        while True:
            await websocket.receive_text()

    except WebSocketDisconnect:
        manager.disconnect(client_id, websocket)


@app.get("/download-pdf/{session_id}")
def download_pdf(session_id: str):
    """
    Objective 5.4 — serves the PDF generated by the /generate-pdf
    background task. 404s if the PDF isn't ready yet (or generation
    failed) rather than blocking/waiting on it.
    """
    path = get_pdf_path(session_id)

    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail="PDF not found. It may still be generating or generation failed.",
        )

    return FileResponse(
        path=str(path),
        media_type="application/pdf",
        filename=f"trip-{session_id}.pdf",
    )


@app.get("/")
def root():
    return {"status": "ok"}