version = 0.1

[default.deploy.parameters]
stack_name = "travelguru-agent-service"
resolve_s3 = true
s3_prefix = "travelguru-agent-service"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
[default.global.parameters]
region = "ap-south-1"
