"""
Standalone latency benchmark: time-to-first-byte for ElevenLabs'
Flash v2.5, Turbo v2.5, and Multilingual v2 models, real streaming
calls to the real API.

Deliberately has ZERO dependency on anything else in this repo --
run it from anywhere with `pip install requests` and your own
ELEVENLABS_API_KEY. This is exactly what "no app dependencies" in the
brief meant: this script has to still work after voice/ is deleted
around it, for as long as you keep this one file.

Model IDs and the streaming endpoint confirmed against ElevenLabs' own
docs (2026-08-11, elevenlabs.io/docs/api-reference/text-to-speech):
eleven_flash_v2_5, eleven_turbo_v2_5, eleven_multilingual_v2. TTFB is
only a meaningful number against the STREAMING endpoint
(/v1/text-to-speech/{voice_id}/stream) -- the non-streaming convert
endpoint would only give total latency, not time-to-first-byte.

I could not run this myself -- it needs a real ELEVENLABS_API_KEY,
which I don't have. Every number in this file's docstring or any
report generated by it is real only once you've actually run it.

Usage:
    pip install requests
    export ELEVENLABS_API_KEY=your_real_key
    python latency_bench.py
"""

from __future__ import annotations

import argparse
import csv
import os
import statistics
import sys
import time

import requests

MODELS = {
    "flash_v2_5": "eleven_flash_v2_5",
    "turbo_v2_5": "eleven_turbo_v2_5",
    "multilingual_v2": "eleven_multilingual_v2",
}

# A widely-available default ElevenLabs voice (Rachel) -- override with
# --voice-id if your account uses a different one. Voice choice
# shouldn't materially affect TTFB comparisons between models; it's
# held constant across all three so it isn't a confound.
DEFAULT_VOICE_ID = "21m00Tcm4TlvDq8ikWAM"

BENCH_TEXT = (
    "Your trip to Goa is ready. Three days, flights on IndiGo, "
    "a hotel near the beach, and clear skies most of the week."
)


def measure_ttfb(api_key: str, voice_id: str, model_id: str) -> float:
    """
    Returns time-to-first-byte in seconds -- wall clock from just
    before sending the request to the moment the first non-empty
    chunk of audio arrives, not the moment the whole response
    finishes (that's total latency, a different, less relevant number
    for a live voice conversation where the caller starts hearing
    audio before generation is fully done).
    """
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/stream"
    headers = {"xi-api-key": api_key, "Content-Type": "application/json"}
    payload = {"text": BENCH_TEXT, "model_id": model_id}

    start = time.perf_counter()
    with requests.post(url, headers=headers, json=payload, stream=True, timeout=30) as response:
        response.raise_for_status()
        for chunk in response.iter_content(chunk_size=1024):
            if chunk:
                return time.perf_counter() - start
    raise RuntimeError(f"No audio bytes received for {model_id}")


def run_benchmark(api_key: str, voice_id: str, runs_per_model: int) -> dict[str, list[float]]:
    results: dict[str, list[float]] = {name: [] for name in MODELS}

    for label, model_id in MODELS.items():
        print(f"\n--- {label} ({model_id}) ---")
        for i in range(runs_per_model):
            try:
                ttfb = measure_ttfb(api_key, voice_id, model_id)
                results[label].append(ttfb)
                print(f"  run {i + 1}/{runs_per_model}: {ttfb * 1000:.0f} ms")
            except Exception as exc:
                print(f"  run {i + 1}/{runs_per_model}: FAILED ({exc})", file=sys.stderr)

    return results


def summarize(results: dict[str, list[float]]) -> None:
    print("\n=== Summary (time-to-first-byte, milliseconds) ===")
    print(f"{'Model':<18}{'n':<6}{'mean':<10}{'p50':<10}{'p95':<10}{'min':<10}{'max':<10}")
    for label, samples in results.items():
        if not samples:
            print(f"{label:<18}0 (all runs failed)")
            continue
        sorted_samples = sorted(samples)
        p50 = sorted_samples[len(sorted_samples) // 2]
        p95 = sorted_samples[int(len(sorted_samples) * 0.95)]
        print(
            f"{label:<18}{len(samples):<6}"
            f"{statistics.mean(samples) * 1000:<10.0f}"
            f"{p50 * 1000:<10.0f}"
            f"{p95 * 1000:<10.0f}"
            f"{min(samples) * 1000:<10.0f}"
            f"{max(samples) * 1000:<10.0f}"
        )


def write_csv(results: dict[str, list[float]], path: str) -> None:
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["model", "run", "ttfb_ms"])
        for label, samples in results.items():
            for i, ttfb in enumerate(samples):
                writer.writerow([label, i + 1, round(ttfb * 1000, 1)])
    print(f"\nRaw results written to {path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--voice-id", default=DEFAULT_VOICE_ID)
    parser.add_argument("--runs", type=int, default=50)
    parser.add_argument("--out", default="latency_results.csv")
    args = parser.parse_args()

    api_key = os.getenv("ELEVENLABS_API_KEY")
    if not api_key:
        print("ELEVENLABS_API_KEY is not set.", file=sys.stderr)
        sys.exit(1)

    results = run_benchmark(api_key, args.voice_id, args.runs)
    summarize(results)
    write_csv(results, args.out)
